# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AlzStudy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AlzStudy

  pod 'Moya'
  pod 'ReactiveSwift'
  pod 'Realm'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'

  

  target 'AlzStudyTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
